### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by llcc**

### CODE REVIEW

**Comment by Kinneyzhang** [comment]
Thanks for your pull request! I have learned a lot techniques about how to write good Elisp code from your PR. The only problem is the indentation, your indentation fix does not displayed well in my emacs, mine is well displayed. I don't know the reason.

**Comment by llcc** [comment]
thanks for accepting those PRs. Basically they do not change any behavior of your package, except some coding optimizations. 

Well, it seems that you use both space and tab for indenting. Mixing of them may cause some indentation problem.

**Comment by Kinneyzhang** [comment]
I use the following code to indent buffer or region, have you got the idea what's the problem here?

```emacs-lisp
;; indent buffer
(defun indent-buffer()
  (interactive)
  (indent-region (point-min) (point-max)))

(defun indent-region-or-buffer()
  (interactive)
  (save-excursion
    (if (region-active-p)
	(progn
	  (indent-region (region-beginning) (region-end))
	  (message "Indent selected region."))
      (progn
	(indent-buffer)
	(message "Indent buffer.")))))
```

**Comment by llcc** [comment]
`(setq-default indent-tabs-mode nil)` will disable tab indentation by only using space. please check [Emacs wiki: no tabs](https://www.emacswiki.org/emacs/NoTabs). I also suggest you to use the following two awesome elisp-coding packages:

1. [lispy](https://github.com/abo-abo/lispy)
2. [aggressive-indent](https://github.com/Malabarba/aggressive-indent-mode)

**Comment by Kinneyzhang** [comment]
Thanks!

**Pull request merged**
